### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by edonyM** [edonyM/toolkitem#5]
- [x] redefine this project
- [x] pyswiger.sh enhancement with protection and help comments
- [x] customized encrypt and decrypt python module
- [x] blog management tools
- [x] ~~security tool [Dmitry](http://tools.kali.org/information-gathering/dmitry)~~
- [x] ...

**Comment by edonyM** [comment]
https://github.com/edonyM/toolkitem/commit/3d73e0c65e818c9f6b3a209ec00bf664b8f18948
